### ISSUE TITLE
"groupBy" throws Converting circular structure to JSON

### ISSUE THREAD

**Issue by Errvald** [a8m/angular-filter#119] opened 2015-05-15 22:37 UTC
I have something like this:
````
users = [
     { id: 1, location: "Japan", location_id: 1},
     { id: 2, location: "Germany", location_id: 2},
     { id: 5, location: "Germany", location_id: 2},
     { id: 3, location: "France", location_id: 3},
     { id: 4, location: "France", location_id: 3}
]

  <li ng-repeat="(key, value) in users | groupBy: 'location_id'">
     {{key}}
  </li>
````

Getting ``TypeError: Converting circular structure to JSON
    at Object.stringify (native)`` 

It works with ``countBy`` but with that I don't have access to ``location``, and I can't do this:

````
- Germany (2)
- France (2)
- Japan (1)
````

**Comment by a8m** [comment] 2015-05-16 07:15
Can you please provide some fiddle/jsbin example?
Thanks @Errvald

**Comment by a8m** [comment] 2015-05-16 07:57
PTAL @Errvald -  [example](http://jsbin.com/vofeyo/1/edit?html,js,output)

**Comment by hughes** [comment] 2015-07-09 18:47
I also ran into this today, but for some reason can't reproduce it when recreating a circular reference in the example...

**Comment by Wasmoo** [comment] 2015-09-17 20:53
groupBy tries to create a hash out of the arguments using toJson, which dies on circular references. To recreate, use objects that refer to each other, as in this example:

http://plnkr.co/edit/41jlNbrITkz8WSUbybV5?p=preview

**Comment by Wasmoo** [comment] 2015-09-17 20:56
```javascript
<!DOCTYPE html>
<html ng-app="plunker">

  <head>
    <meta charset="utf-8" />
    <title>AngularJS Plunker</title>
    <script>document.write('<base href="' + document.location + '" />');</script>
    <link rel="stylesheet" href="style.css" />
    <script data-require="angular.js@1.4.x" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js" data-semver="1.4.5"></script>
    <script data-require="angular-filter@*" data-semver="0.5.2" src="https://cdnjs.cloudflare.com/ajax/libs/angular-filter/0.5.2/angular-filter.js"></script>
    <script src="app.js"></script>
  </head>

  <body ng-controller="MainCtrl">
    Ages:
    <div ng-repeat="(age, peps) in people | groupBy : 'age'">
      {{age}}
    </div>
    <script>
      var app = angular.module('plunker', ['angular.filter']);
      
      app.controller('MainCtrl', function($scope) {
        var alice = {
          name: "Alice",
          age: 20
        };
        
        var bob = {
          name: "Bob",
          age: 40
        };
      
        var calvin = {
          name: "Calvin",
          age: 20
        };
      
        alice.parent = bob;
        bob.child = alice;
        
        $scope.people = [alice, bob, calvin];
      });
      
    </script>
    
  </body>

</html>
```

**Comment by Wasmoo** [comment] 2015-09-18 13:53
JSFiddle version
https://jsfiddle.net/WASMOO/tezjudL0/2/

**Comment by Wasmoo** [comment] 2015-09-18 15:56
The following code is a temporary hack that works for me (replacing `function getHashKey` near angular-filter.js:2092)

```javascript
    /**
     * Creates a copy of the given object, but replaces duplicate children
     * @param  orig The object to copy
     * @param  objs Array of objects that were already found
     * @return the resulting copy
     */
    var getHashHelper = function(orig, objs) {
      //Primitives are not copied
      if (!isObject(orig)) {
        return orig;
      }

      //Return replacement if reference already exists
      var index = objs.indexOf(obj);
      if (index !== -1) {
        return 'HashHelperObject:'+index;
      }

      //Add this object to the reference list
      objs.push(orig);

      //Recursively create a copy of orig
      var copy;
      if (isArray(orig)) {
        copy = [];
      } else {
        copy = {};
      }

      for (var n in orig) {
        copy[n] = getHashHelper(obj, objs);
      }

    };

    /**
     * @description
     * get `HashKey` string based on the given arguments.
     * @param fName
     * @param args
     * @returns {string}
     */
    function getHashKey(fName, args) {
      return [fName, angular.toJson(getHashHelper(args, []))]
        .join('#')
        .replace(/"/g,'');
    }
```

**Comment by PureDeveloper** [comment] 2015-10-04 01:25
Wasmoo, I tried your temp hack and get the following error of: 
```
Error: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('file') does not support selection.
    at Error (native)
```

error points to something to do with: 
copy[n] = getHashHelper(orig[n], objs); 

Any ideas?

**Comment by a8m** [comment] 2015-10-04 10:24
Fixed via __0.5.7__
I'm closing it. If there's still any problem, do not hesitate to reopen.

Thanks.

**Closed by a8m** 2015-10-04 10:24 UTC

**Comment by PureDeveloper** [comment] 2015-10-06 19:56
@a8m, that fixed it. Thanks for the fast response and fix.

**Comment by deepthiravadi** [comment] 2015-11-09 21:12
Hi, I am getting this error
5angular.js:11699 TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at http://192.168.32.163/js/angular/angular.min.js:6:387
    at http://192.168.32.163/js/angular/angular.min.js:234:494
    at Object.fn (http://192.168.32.163/js/angular/angular.min.js:123:30)
    at m.$digest (http://192.168.32.163/js/angular/angular.min.js:124:114)
    at m.$apply (http://192.168.32.163/js/angular/angular.min.js:127:12)
    at l (http://192.168.32.163/js/angular/angular.min.js:81:327)
    at P (http://192.168.32.163/js/angular/angular.min.js:85:449)
    at XMLHttpRequest.H.onload (http://192.168.32.163/js/angular/angular.min.js:86:462)

I tried your hack,but no luck.can you please help.Thanks!

**Comment by a8m** [comment] 2015-11-09 21:37
Hi @deepthiravadi 
Can you please provide some fiddle/jsbin that demonstrate that?

Thanks.

**Comment by deepthiravadi** [comment] 2015-11-09 21:40
Sorry, I cant do that..I didnt write the code and the js files are so many ,so i dont know the code.But it loads a gnatt chart for a project and it loads for all other projects except for this one.It throws that error.Iam trying to console.log outputs but no clue whats causing it..The array has objects and child objects.

**Comment by deepthiravadi** [comment] 2015-11-09 21:50
This is the code and trying to out put chart data  which is    $scope.gantt_data

function project_setupPage($rootScope, $scope, $http, noty, $interval, $timeout, $route, $location, $window, project_id) {
    $scope.type = 'Edit';

    $scope.gantt_options = {
        groupDisplayMode: 'group',
        currentDate: 'line',
        currentDateValue: new Date(),
        timeFrames: {
            'day': {
                start: moment('8:00', 'HH:mm'),
                end: moment('18:00', 'HH:mm'),
                working: true,
                default: true
            },
            'weekend': {
                working: false
            },
            'holiday': {
                working: false,
                color: 'red',
                classes: ['gantt-timeframe-holiday']
            }
        },
        columnWidth: 280,
        treeHeaderContent: 'T{{row.model.name}}',
        columnsHeaderContents: {
            'model.name': '<i class="fa fa-align-justify"></i> {{getHeader()}}'
        },
        dateFrames: {
            'weekend': {
                evaluator: function (date) {
                    return date.isoWeekday() === 6 || date.isoWeekday() === 7;
                },
                targets: ['weekend']
            }
        },
        headers: function (view_scale) {
            if (view_scale === '1 month') {
                return ['year', 'month'];
            } else if (view_scale === '3 months') {
                return ['year', 'quarter'];
            } else {
                return ['month', 'week'];
            }
        },
        headersFormats: {
            hour: 'hh:mmA',
            week: function (column) {
                return column.date.format('MMM D') + ' - ' + moment(column.date).add(6, "days").format('MMM D');
            }
        },
        tooltip_content: function (task) {
            return "<small>" + task.model.name + "</small>";
        },
        view_scale: function () {
            var weeks = weeks_between(new Date($scope.start_date), $scope.final_end_date);
            if (weeks > 12) {
                return '1 month';
            } else if (weeks > 22) {
                return '3 months';
            } else {
                return 'week';
            }
        },
        api: function (api) {
            // API Object is used to control methods and events from angular-gantt.
            $scope.api = api;

            api.core.on.ready($scope, function () {
                // Add some DOM events
                api.directives.on.new($scope, function (directiveName, directiveScope, element) {
                    if (directiveName === 'ganttRowLabel') {
                        element.bind('click', function (event) {
                            event.stopPropagation();
                            if (directiveScope.row.tasks.length > 0) {
                                var task_template = directiveScope.row.tasks[0].model.data.template_task;
                                $scope.openTask(task_template);
                            }
                        });
                    } else if (directiveName === 'ganttTask') {
                        element.bind('click', function (event) {
                            event.stopPropagation();
                            var task_template = directiveScope.task.model.data.template_task;
                            $scope.openTask(task_template);
                        });
                    }
                });
            });

            $scope.loadProject(false);
        }
    };

    $scope.openTask = function (task_template) {
        if ($scope.project.project_status_id === 4) {
            return;
        }

        // Is it already started and has multiple tasks
        if (typeof task_template.live_tasks !== 'undefined' && (task_template.live_tasks.length > 1 || (task_template.live_tasks.length > 0 && task_template.task_occurrence_id === 2))) {
            $window.open('#/project/' + task_template.project_id + '/' + task_template.id);
        } else if (typeof task_template.task_id !== 'undefined' && typeof task_template.live_tasks !== 'undefined' && task_template.live_tasks.length === 1) { // Is it already started and has a single tasks
            $window.open('#/queue/' + task_template.department_id + '/edit/' + task_template.task_id);
        } else if (task_template.duration > 0) {
            noty.show('You are editing the template for a task that has not yet been started.', 'warning');
            $location.path('/project/' + task_template.project_id + '/task/' + task_template.id);
        }
        $scope.$apply();
    };

    $scope.tasks_building = false;
    $scope.previous_task_built_total = 0;
    $scope.previous_closed_total = -1;
    $scope.load_time = new Date();

    // Load template tasks and build Gnatt chart.
    $scope.loadProject = function (shallow) {
        //$scope.gantt_options.currentDateValue = new Date();
        getProject($rootScope, $http, noty, project_id, function (pStatus, pData) {
            if (pStatus === 'success') {
                if (pData.expected_task_cnt !== 0 && pData.actual_task_cnt !== pData.expected_task_cnt) {
                    $scope.tasks_building = true;
                } else {
                    if ($scope.tasks_building || (typeof $scope.project !== 'undefined' && pData.expected_task_cnt !== $scope.project.expected_task_cnt)) {
                        $scope.tasks_building = false;
                        $route.reload();
                    }
                }

                var d = new Date();
                var t = d.getTime();
                if (t - 15000 > $scope.load_time.getTime() && typeof $scope.project !== 'undefined' && $scope.previous_closed_total !== -1 && $scope.previous_closed_total !== pData.closed_cnt) {
                    $route.reload();
                }

                if (pData.actual_task_cnt <= 0 || pData.expected_task_cnt <= 0) {
                    $scope.task_setup_progress = 0;
                } else {
                    $scope.task_setup_progress = Math.floor((pData.actual_task_cnt) / (pData.expected_task_cnt) * 1000) / 10;
                }

                if (shallow) {
                    $scope.project.actual_task_cnt = pData.actual_task_cnt;
                    $scope.project.expected_task_cnt = pData.expected_task_cnt;
                    $scope.project.progressing_flag = pData.progressing_flag;
                } else {
                    $scope.project = pData;
                    $scope.previous_closed_total = pData.closed_cnt;

                    if (pData.project_status_id === 4) {
                        $scope.gantt_options.currentDate = 'none';
                    }

                    apiCall($rootScope, $http, noty, 'GET', 'ms/project/site_list/' + project_id, undefined, function (pslStatus, pslData) {
                        if (pslStatus === 'success') {
                            $scope.project_site_list = pslData;

                            // Found in /content/project/template/controllers/template.js
                            if (typeof $scope.project !== 'undefined') {
                                console.log()
                                $scope.start_date = new Date($scope.project.started_date);
                                $scope.start_date = $scope.start_date.toISOString();

                                console.log($scope.project.tasks);

                                var temp = buildGanttChartData($scope, $scope.project.tasks, true);
                                $scope.gantt_data = temp;
                                //  console.log($scope.gantt_data);
                            }

                            $scope.loaded = true;
                        }
                    });
                }
            }
        }, true, shallow);
    };

    var project_status_check = $interval(function () {
        if ($scope.loaded) {
            $scope.loadProject(true);
        }
    }, 5000);

    $scope.$on('$destroy', function () {
        if (project_status_check) {
            $interval.cancel(project_status_check);
        }
    });
}

**Comment by deepthiravadi** [comment] 2015-11-09 21:53
the object data is something like this

1: Object
children: Array[0]
classes: Array[1]
id: "8f009ce4-e94f-051b-d3ca-3e33e62e8ce0"
name: "Finalize and Promote P&L"
tasks: Array[1]
__proto__: Object
